### ISSUE TITLE
Aesthetics outside of aesthetics 

### ISSUE THREAD

**Issue by DominiqueMakowski** [jtlandis/ggside#12]
For most of ggplot's geoms, aesthetics such as `color` can be either specified within the `aes()` field, in which case it varies according to the data, or outside, in which case it is changed globally.

However, this doesn't seem to be the case for ggside, in which a general color specified for the side density (that should *not* be considered as a proper `aes(color)`, but merely as a general and purely-aesthetic feature) gets mistaken as if it was within an `aes()` field: as a result, it gets added to the legend.

``` r
library(ggplot2)

p <- ggplot(iris, aes(x = Sepal.Length, y = Petal.Width)) +
  geom_point(color = "grey") +
  geom_smooth(aes(color = Species), method = "lm", se = FALSE) 
p
```

![](https://i.imgur.com/glxkk6I.png)

In the above basic example, there's a general color specified for the points, and an aesthetic color specified for the lines. The legend correctly only shows the latter.

``` r
p + ggside::geom_xsidedensity(color = "grey")
```

![](https://i.imgur.com/PFWB8c0.png)

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

However, adding a side-density with a general color adds it to the legend. Any workaround? Thanks!

The most consistent behaviour would be that only aesthetics wrapped within `aes()` are added to the legend.

**Comment by jtlandis** [comment]
whoa - this is definitely a bug. I'm not immediately sure where the issue would be but I will have a look!

**Comment by jtlandis** [comment]
I found the issue and the dev version is building now. I will merge this to the master branch after it passes the build
