### ISSUE TITLE
`ggside` plots can't be combined using `patchwork` package

### ISSUE THREAD

**Issue by IndrajeetPatil** [jtlandis/ggside#15]
Ideally, this should work since the class of objects from `ggside` is still `ggplot`, but my guess is that overwriting `+.gg` method from `ggplot2` creates problems for `patchwork`:

``` r
options(error = traceback)
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
library(ggplot2)
library(patchwork)

# let's create two different plots
p1 <- ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  geom_xsidehistogram(aes(y = after_stat(count))) 

p2 <- ggplot(mtcars, aes(hp, drat)) + geom_point() +
  geom_xsidehistogram(aes(y = after_stat(count))) 

# combine them using patchwork
wrap_plots(list(p1, p2))
#> Error in match(x, table, nomatch = 0L): 'match' requires vector arguments
#> 8: object$ggside$scales %in% c("fixed", "free", "free_x", "free_y")
#> 7: make_ggside(plot, ggside)
#> 6: as_ggside(p, e2)
#> 5: add_gg.ggside(e1, e2, e2name)
#> 4: add_gg(e1, e2, e2name)
#> 3: `+.gg`(init, x[[i]])
#> 2: Reduce(`+`, plots, init = plot_filler())
#> 1: wrap_plots(list(p1, p2))
```

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jtlandis** [comment]
Hello! This is actually a known issue and should be fixed on the master branch of the github repository. I have a wait a bit longer before I can update the CRAN version. Please see issue #13 

And to show you I'm not lying, here is your reprex with the changes on the master branch

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
library(ggplot2)
library(patchwork)

# let's create two different plots
p1 <- ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  geom_xsidehistogram(aes(y = after_stat(count))) 

p2 <- ggplot(mtcars, aes(hp, drat)) + geom_point() +
  geom_xsidehistogram(aes(y = after_stat(count))) 

# combine them using patchwork
wrap_plots(list(p1, p2))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/fQoaNU3.png)

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Awesome!! Thanks a lot. I never doubted you 😉 

Is there any particular reason why you need to wait before submitting to CRAN?

I am asking because I would like to rely on `ggside` in my [package](https://indrajeetpatil.github.io/ggstatsplot/) and I would prefer to submit it to CRAN sooner than later.

**Comment by jtlandis** [comment]
I confused myself, I saw that I made a bit ago and didn't realize that my package has been on CRAN for 2 month. After re-reading [CRAN's resubmission policies](https://r-pkgs.org/release.html) that says package updates shouldn't come no sooner than 1-2 months, so I should be within the time frame. I might not have time to get the submission done today, but I will try to get it drafted over the weekend.

**Comment by IndrajeetPatil** [comment]
Sounds good, thanks! :)

**Comment by IndrajeetPatil** [comment]
Let me know when the `ggside` update makes it to CRAN. I will prepare my submission update accordingly.

**Comment by jtlandis** [comment]
I just pushed the `dev` branch to CRAN, I'll post again when the submission is accepted.

**Comment by IndrajeetPatil** [comment]
Great!

**Comment by IndrajeetPatil** [comment]
Any update from CRAN?

I don't see it here (https://lockedata.github.io/cransays/articles/dashboard.html), so I am guessing the submission was asked to be revised or something?

**Comment by jtlandis** [comment]
I submitted the package using `devtools::release()` but since then have not received a confirmation email. I think I'll resubmit the old fashion way, by building the tar.gz

**Comment by IndrajeetPatil** [comment]
You can use this function:
https://rdrr.io/cran/devtools/man/submit_cran.html

**Comment by IndrajeetPatil** [comment]
I see it on CRAN! Thanks a lot for quick responses. :)
