### ISSUE TITLE
changing scales removes side histograms

### ISSUE THREAD

**Issue by IndrajeetPatil** [jtlandis/ggside#17]
This works as expected:

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
library(ggplot2)

# works
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/R60RT6W.png)

But I (and I am guessing a lot of other users as well) will at times change the scales. In this case, the side histograms disappear:

``` r
# removes y-axis histogram
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  ggplot2::scale_x_continuous(breaks = seq(1, 6, 1), limits = (c(1, 6))) +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing missing values (geom_xsidebar).
#> Warning: Removed 30 rows containing missing values (geom_ysidebar).
```

![](https://i.imgur.com/g0vM7r5.png)

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jtlandis** [comment]
At first I thought this was a bug, but then I stepped through the code and saw that everything was being trained correctly. The issue is that `scale_x_continuous` will apply to all panel's x-axis by default. The `limit` parameter in this case, was clipping the histogram data. If you want to specify the main panel's axes without affecting the side panels, use `scale_xsidey_*()` for the y-axis of the xside panel, and `scale_ysidex_*()` for the x-axis fo the yside panel.

``` r
library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1, 6, 1),
                     limits = (c(1, 6))) + # histograms have their lower data specified at 0 - this limit removes the data
  geom_histogram(aes(y = mpg), orientation = "y", inherit.aes = F) 
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 30 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/Q0cd3Sc.png)

``` r

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1, 6, 1), limits = (c(1, 6))) +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count))) +
  scale_ysidex_continuous()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing missing values (geom_xsidebar).
```

![](https://i.imgur.com/pBUtTRy.png)

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Wunderbar! Worked a like a charm.

Thanks for walking me through the process and explaining why it was not working :)
I will leave it up to you if you want to include an example like this in the documentation somewhere for the users.

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1, 6, 1), limits = (c(1, 6))) +
  scale_y_continuous(breaks = seq(10, 40, 10), limits = (c(10, 40))) +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count)))  +
  scale_ysidex_continuous() +
  scale_xsidey_continuous()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing missing values (geom_xsidebar).
#> Warning: Removed 2 rows containing missing values (geom_ysidebar).
```

![](https://i.imgur.com/ujTdY5U.png)

<sup>Created on 2021-07-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jtlandis** [comment]
If you have any recommendations on where documentation should go, I'd love to know. Obviously I could just put an example in the `scale_xsidey_*` functions, but I suspect most users will not discover those functions without someone telling them about it. 
Currently, their existence is mentioned in the NEWS file, and there are a few examples added to the end of `vignette('ggside_basic_usage')`. Have any suggestions?

**Comment by IndrajeetPatil** [comment]
Hmm, I think you can add the example like the following to individual function documentation.

For example, for `geom_*sidehistogram`:

```r
library(ggside)
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1, 6, 1), limits = (c(1, 6))) +
  scale_y_continuous(breaks = seq(10, 40, 10), limits = (c(10, 40))) +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count)))  +
  scale_ysidex_continuous() +
  scale_xsidey_continuous()
```

Similar example can also be used for `geom_*sidedensity`, etc.

Currently, the [docs](https://rdrr.io/cran/ggside/man/geom_xsidehistogram.html) only show how to display the `ggside` `geom_`s, but often the users will not stop at that and will also add `ggplot2` geoms. And so the if the manual examples can also make clear that you _can_ mix `geom_` functions from these packages together, that would be nice. This might seem obvious to us, but might be a good encouragement for the beginners to get their hands dirty by mixing `geom_`s from different packages. Does that make sense?
