### ISSUE TITLE
clarifying difference between `ggExtra` and `ggside` in documentation

### ISSUE THREAD

**Issue by IndrajeetPatil** [jtlandis/ggside#18]
Before `ggside`, `ggExtra` was probably the most used package to display marginal distributions. 

So it would be nice if the documentation can clarify how `ggside` differs from it, especially in computing density and histogram, which look pretty different across these two packages.

What do you think?

# `ggExtra`

``` r
library(ggplot2)

p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()

library(ggExtra)

ggMarginal(p, type = "densigram")
```

![](https://i.imgur.com/OQdfp8d.png)

# `ggside`

``` r
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

p +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count))) +
  geom_xsidedensity(aes(y = after_stat(count))) +
  geom_ysidedensity(aes(x = after_stat(count)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/RqJ2CJd.png)

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jtlandis** [comment]
After spending a bit too much time delving into `ggExtra`, I found out where the difference lies. `ggExtra` will map the histogram and density stat calculations to "density", AND will add a parameter called `boundary` to the histogram layer.

For the top layer the boundary comes out to 1.513, and for the right margin it comes out to 10.4. The internals calculate this value by grabbing the scale ggproto object and pulling out a limit function.

I might consider writing a vignette, but for the most part I think this makes it pretty clear. I personally don't know how changing the boundary affects the interpretation of the density distribution, but in any case, calculating the boundary in the way that `ggExtra` does is out of the scope of `ggside`, as you will need to have the Scales object made.

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
library(ggExtra)
p <- ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  theme_classic()
ggMarginal(p, type = "densigram")
```

![](https://i.imgur.com/mslH5AX.png)

``` r

p +
  geom_xsidehistogram(aes(y = after_stat(density)), color = "black", boundary = 1.513) +
  geom_ysidehistogram(aes(x = after_stat(density)), color = "black", boundary = 10.4) +
  geom_xsidedensity() +
  geom_ysidedensity() +
  scale_ysidex_continuous(guide = guide_axis(angle = 90)) +
  theme(ggside.panel.scale = .2)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/uu8xtrx.png)

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Thank you so much for taking such a deep dive into `ggExtra` to figure this out! Much appreciated.

I will stick to `ggside`'s defaults because I find the counts on the axes much more informative than whatever is shown after boundary-parameter based density computation happens.

I will close this for now and let you decide if you wish to document this somewhere.

**Comment by jtlandis** [comment]
`geom_(x|y)side histogram` will map `after_stat(count)` by default, and `geom_(x|y)side density` will map `after_stat(density)` by default. I think in a previous issue we talked about the potential scaling issue between these two defaults - so to make `ggside` a drop and replace for `ggExtra`, I'd recommend you use `after_stat(density)` mapping for everything. 👍

**Comment by IndrajeetPatil** [comment]
Thanks!

>  to make `ggside` a drop and replace for `ggExtra`

I think I am just going to stick to `ggside`'s defaults, which I find to be more straightforward to interpret :)
