### ISSUE TITLE
simultaneously displaying both histogram and density plot on axes

### ISSUE THREAD

**Issue by IndrajeetPatil** [jtlandis/ggside#2]
Hi again!

I was playing around with different `geom`s and one odd thing I noticed is that when both the histogram and density plots are simultaneously displayed, the density plot is pretty much flat. Is that expected?

I am displaying the output from `ggExtra` for a comparison.

# `ggside`

``` r
library(ggside)

p <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point()

p +
  geom_xsidehistogram(aes(x = wt), inherit.aes = FALSE) +
  geom_ysidehistogram(aes(y = mpg), inherit.aes = FALSE) +
  geom_xsidedensity(aes(x = wt), inherit.aes = FALSE) +
  geom_ysidedensity(aes(y = mpg), inherit.aes = FALSE)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/eqrVGi7.png)

# `ggExtra`

``` r
library(ggplot2)
library(ggExtra)

p <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point()

ggMarginal(p, type = "densigram")
```

![](https://i.imgur.com/ia98Gsv.png)

<sup>Created on 2021-03-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jtlandis** [comment]
Hello again!

This is not a mistake and is actually just the true scaling of the default `density` computed variable

Here is a list of the available computed variables that `StatDensity` creates for a set of data:

## Computed variables

* density
  * density estimate
* count
  * density multiplied by the number of points - useful for stacked density plots
* scaled
  * density estimate, scaled to maximum of 1
* density
  * alias for scaled, to mirror the syntax of `stat_bin()`

You can see the difference in scale if you were to only plot the `geom_*sidedensity`

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

p <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point()

p +
  # geom_xsidehistogram(aes(y = after_stat(count))) +
  # geom_ysidehistogram(aes(x = after_stat(count))) +
  geom_xsidedensity(aes(y = after_stat(density))) +
  geom_ysidedensity(aes(x = after_stat(density)))
```

![](https://i.imgur.com/mHHpNaa.png)

Alternatively, you could use `after_stat(scaled)` and then multiply by a value that fits pretty well. 3 seems like a good value

``` r

p +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count))) +
  geom_xsidedensity(aes(y = after_stat(scaled)*3)) +
  geom_ysidedensity(aes(x = after_stat(scaled)*3))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/JWIyvkh.png)

If you rather not guess, maybe `after_stat(count)` will reproduce a more similar result.

``` r

p +
  geom_xsidehistogram(aes(y = after_stat(count))) +
  geom_ysidehistogram(aes(x = after_stat(count))) +
  geom_xsidedensity(aes(y = after_stat(count))) +
  geom_ysidedensity(aes(x = after_stat(count)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/3M25BKq.png)

<sup>Created on 2021-03-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Excellent! `after_stat(count)` solution is what I was looking for! :)

**Comment by eibol1** [comment]
Is it possible to plot two histograms on the sides of discrete values? 

how you can do it separately ?
