### ISSUE TITLE
Edge case bug when the ggside geom is passed within a list

### ISSUE THREAD

**Issue by DominiqueMakowski** [jtlandis/ggside#24]
In ggplot, an alternative way of plotting multiple geoms "at once" is to pass them in a list, like so:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.0.5
library(ggside)
#> Warning: package 'ggside' was built under R version 4.0.5
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

p <- ggplot(mtcars, aes(x = mpg, y = wt))

l <- list(geom_point(), geom_smooth())

p + l
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/hicnREu.png)

Unfortunately (as this is a behaviour helpful when building packages), this doesn't work with ggside's geoms, which gets plotted "within" the plot:

```r
l <- list(geom_point(), geom_smooth(), ggside::geom_xsidedensity())

p + l
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/qOsQ4E2.png)

<sup>Created on 2021-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Is there any chance of addressing that? Thanks!

**Comment by jtlandis** [comment]
This is a relatively simple fix. Thank you for catching!

**Comment by jtlandis** [comment]
With the latest commit (442c83db4cca57bc9cc962be563fbd7df0463d86), this should be fixed on the master branch.

**Comment by fredcallaway** [comment]
Thanks for taking the time to maintain this awesome package!
