### ISSUE TITLE
Plotting two histograms from discrete data on the x and y axis of a heatmap

### ISSUE THREAD

**Issue by eibol1** [jtlandis/ggside#32]
Hi there, 

I have a Heatmap where I have discrete values on both sides (y=SYMBOL, x=sample, I cannot show all data), filled with another variable (type of variant):
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/88188797/166499798-b53a5dd4-580c-4b0a-8fa9-754cc0929959.png">

I want to add two histograms on both x and y axis with `geom_xsidehistogram()` and `geom_ysidehistogram()` filled with the same variable but I have error:

```
Error in `f()`:
! stat_count() can only have an x or y aesthetic.
```
If i only add one histogram there is no problem, but the problem comes when I try to plot both histograms as mentioned. 

How can I avoid that error?

If you need more info about the code, let me know please.

**Comment by jtlandis** [comment]
I’m not sure what your code looks like so I do not know if I can accurately help you.
here is a reproducible example

``` r
library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
```

Let’s make some dummy data

``` r
set.seed(1234)
df <- expand.grid(
  cols = sprintf("%02d", 1:12),
  rows = LETTERS[1:8]
)
indices <- sample(1:96, 50)
variants <- sample(factor(c("deletion","insertion","SNV","substitution")), size = 50, replace = T, prob = c(.2,.2,.5,.1))
df_sub <- df[indices,]
df_sub$variants <- variants


p <- ggplot(df_sub, aes(x = cols, y = rows)) +
  geom_tile(aes(fill = variants)) +
  viridis::scale_fill_viridis(discrete = T)
p
```

![](https://i.imgur.com/rk0d8UO.png)

histograms are usually placed on a continuous scale - namely, `geom_xsidehistogram()`
expects the xside to be continuous. Additionally a histogram plots to a continuous scale as well.
The problem is that the main plot maps to the discrete scale. We can get around what the side
panels scales are, namely `xsidey` (the y axis of the xside panel) and the `ysidex` (the x-axis of the yside panel)
with the `scale_(x|y)side(y|x)_(continuous|discrete)()` functions.
However, the geom\_xside*() functions must always share the same scale as the main panel’s x-axis.
the same goes for the geom\_yside*() functions andthe main panel’s y-axis.
here we can use `stat = "count"` to plot the histograms, but this is similar to just using
geom\_xsidebar() - as these do not have notions of binwidth and plot well on a discrete axis

``` r
p + geom_xsidehistogram(stat="count", fill = "lightblue") +
  scale_xsidey_continuous() +
  geom_ysidehistogram(stat = "count", fill = "darkblue") +
  scale_ysidex_continuous()
#> Warning: Ignoring unknown parameters: binwidth, bins, pad

#> Warning: Ignoring unknown parameters: binwidth, bins, pad
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors
#> Warning in Ops.factor(x, range[2]): '>' not meaningful for factors
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors
#> Warning in Ops.factor(x, range[2]): '>' not meaningful for factors
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors
#> Warning in Ops.factor(x, range[2]): '>' not meaningful for factors
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors
#> Warning in Ops.factor(x, range[2]): '>' not meaningful for factors
```

![](https://i.imgur.com/CF723U4.png)

``` r
p + geom_xsidebar(fill = "lightblue") +
  scale_xsidey_continuous() +
  geom_ysidebar(fill = "darkblue") +
  scale_ysidex_continuous()
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors

#> Warning in Ops.factor(x, range[1]): '>' not meaningful for factors
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors
#> Warning in Ops.factor(x, range[2]): '>' not meaningful for factors
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors
#> Warning in Ops.factor(x, range[2]): '>' not meaningful for factors
#> Warning in Ops.factor(x, range[1]): '<' not meaningful for factors
#> Warning in Ops.factor(x, range[2]): '>' not meaningful for factors
```

The unfortunate part of using `scale_(x|y)side(y|x)_(continuous|discrete)()` is that we get those warnings in the Ops.factor method. This is likely because one scale has factors and another has continuous values. 

![](https://i.imgur.com/aCO2T21.png)

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eibol1** [comment]
hi @jtlandis , 

thanks for the quick response. I am trying to do what you did, but I'm trying to fill the histograms with 'variants' but I can't. 

I also tried something different and it worked for me, but I don't know if it is the correct way to proceed: 

`fig <- heatmap_clean + geom_xsidebar(aes(y = after_stat(count), fill=VARIANT_CLASS), position='stack', binwidth = 0.5)  + geom_ysidebar(aes(x = after_stat(count),fill=VARIANT_CLASS), binwidth = 0.5) `

I have these warnings but:

**Comment by eibol1** [comment]
hi @jtlandis ,

thanks for the quick response. I am trying to do what you did, but I'm trying to fill the histograms with 'variants' but I can't.

I also tried something different and it worked for me, but I don't know if it is the correct way to proceed:

`fig <- heatmap_clean + geom_xsidebar(aes(y = after_stat(count), fill=VARIANT_CLASS), position='stack', binwidth = 0.5) + geom_ysidebar(aes(x = after_stat(count),fill=VARIANT_CLASS), binwidth = 0.5)
`
I have these warnings but: 

Warning messages:
1: Ignoring unknown parameters: binwidth 
2: Ignoring unknown parameters: binwidth 

Can you tell me if it is ok? I can see that the plot is ok, but the y_scale from xside plot is missing. Maybe I can add it from the `theme()` function?

If I add `scale_xsidey_continuous()` and `scale_yside_continous()` to the code, I have this error: 

```
Error in unit(rep(just$hjust, n), "npc") : 
  'x' and 'units' must have length > 0
```
What I can do here? 

Thank you in advance, sorry if I am no explaining well the problem or if I am a noob

**Comment by eibol1** [comment]
here is my last code 

> hi @jtlandis ,
> 
> thanks for the quick response. I am trying to do what you did, but I'm trying to fill the histograms with 'variants' but I can't.
> 
> I also tried something different and it worked for me, but I don't know if it is the correct way to proceed:
> 
> `fig <- heatmap_clean + geom_xsidebar(aes(y = after_stat(count), fill=VARIANT_CLASS), position='stack', binwidth = 0.5) + geom_ysidebar(aes(x = after_stat(count),fill=VARIANT_CLASS), binwidth = 0.5) ` I have these warnings but:
> 
> Warning messages: 1: Ignoring unknown parameters: binwidth 2: Ignoring unknown parameters: binwidth
> 
> Can you tell me if it is ok? I can see that the plot is ok, but the y_scale from xside plot is missing. Maybe I can add it from the `theme()` function?
> 
> If I add `scale_xsidey_continuous()` and `scale_yside_continous()` to the code, I have this error:
> 
> ```
> Error in unit(rep(just$hjust, n), "npc") : 
>   'x' and 'units' must have length > 0
> ```
> 
> What I can do here?
> 
> Thank you in advance, sorry if I am no explaining well the problem or if I am a noob

here is the code I have:

```
full <- heatmap_clean + geom_xsidebar(aes(y = after_stat(count), fill=VARIANT_CLASS), position='stack', binwidth = 0.5)  +
        theme(ggside.axis.line.y=element_line(colour = "black"),
               ggside.axis.text.y=element_text(colour='black'))+
        geom_ysidebar(aes(x = after_stat(count),fill=VARIANT_CLASS), binwidth = 0.5) 
```
where heatmap_clean is the first heatmap I showed you, without the y_axis text and ticks and legend.

and the output:

<img width="867" alt="image" src="https://user-images.githubusercontent.com/88188797/166639720-4519f05f-384c-494b-a8b7-00e0f94ed44a.png">

**Comment by eibol1** [comment]
Sorry for commenting too much, I finally solved it: 

The problem was with the heatmap I defined before, which has no y_axis, so the xsideplot was "inheriting" this. I maintained the heatmap as raw as I could, and then I defined the x and y axis of both the xside and yside plots. Everything worked well:

```
heatmap <- ggplot(acumulador, aes(x=sample, y=SYMBOL, xlab=NULL,ylab=NULL)) + 
    geom_tile(aes(fill=VARIANT_CLASS),colour="white", size=0.25) +
    guides(fill=guide_legend(title="Type of variant")) +
    scale_y_discrete() +
    ylab('')+
    scale_fill_viridis(discrete = T) +
    theme(axis.title.x = element_blank(), axis.text.x = element_text(angle=90,hjust = 0.5, size = 8),
          axis.text.y=element_text(size=8))
  
  
    full <- heatmap + geom_xsidehistogram(stat="count", aes(fill = VARIANT_CLASS)) +
      geom_ysidehistogram(stat = "count", aes(fill=VARIANT_CLASS)) +
      scale_ysidex_continuous(position='top')+
      scale_xsidey_continuous()+
      theme(ggside.panel.grid=element_blank(),
            ggside.panel.background=element_blank(),
            ggside.axis.line=element_line(colour = 'black'),
            ggside.axis.text.x.top=element_text(angle=270))
```


<img width="1241" alt="image" src="https://user-images.githubusercontent.com/88188797/166652063-3a46a121-71b0-47ee-9168-a44db6ea5ff9.png">

**Comment by eibol1** [comment]
I close the issue, 

thanks @jtlandis for your suppport! 👍🏼😁

**Comment by jtlandis** [comment]
I'm happy you were able to get to your desired result!
