### ISSUE TITLE
Ops.factor : not meaningful for factors

### ISSUE THREAD

**Issue by jtlandis** [jtlandis/ggside#33]
With the addition of the ability to mix continuous and discrete scales, there arrose an annoying error message that followed the pattern of:

    # Warning messages:
    # 1: In Ops.factor(x, range[1]) : ‘<’ not meaningful for factors
    # 2: In Ops.factor(x, range[2]) : ‘>’ not meaningful for factors

This was supposedly the result of the `oob` default function on `scale_*side*_continuous()` function, as sometimes a factor would make its way into it and prompt a warning in base R. Instead of requesting a pull request, I have added a decorator around this argument that will watch for this pattern and muffle the message if encountered.

    new_oob <- function(f) {
        function(...) {
          withCallingHandlers(
            warning = function(cnd) {
              msg <- conditionMessage(cnd)
              if (grepl("‘(<|>)’ not meaningful for factors", msg)) {
                rlang::cnd_muffle(cnd)
              }
            },
            f(...)
          )
        }
      }

This change will be available on the dev branch shortly

**Comment by jtlandis** [comment]
While I could initiate a fix to our own continuous axis creating the error, there was still the issue with native continuous axis (when mixed with a discrete side axis) producing a warning message. The fix involves on the fly changing of the ScalesList class, and overriding the `get_scales()` method to in addition to pulling the appropriate scale, will then check if it is of `ScaleContinuousPosition` class and then decorate the `oob` member with a muffled condition. This ultimately feels messy but gets the job done.

**Comment by mherold1** [comment]
I am not sure if this is related but I encounter the following issue in ggside 0.2.1:
The plot I tried to make was x vs y both categories and using pointsize (also factor 1,2,3). Then tried to add side barplots (geom_xsidecol, geom_ysidecol) to count the numeric values, used for pointsize in the mainplot, across each category.

![image](https://user-images.githubusercontent.com/10416078/184331775-073503b4-df6d-4d0c-97fa-e55966756a8c.png)

[pdat.zip](https://github.com/jtlandis/ggside/files/9315496/pdat.zip)
```
pdat %>%
  ggplot() +
  geom_point(aes(y = fct_rev(sampleID), x = category, fill = category, size = count), shape = 21, alpha = 0.9) +
  scale_size_manual(values = c(2, 3.5, 5), breaks = c(1,2,3)) +
  scale_fill_manual(values = cat_cols) +
  theme_bw() +
  theme(axis.text.x = element_text(angle =90, hjust= 1, vjust=0.5),
        axis.text.y = element_text(size = 7)) +
  facet_wrap(~is_mixture, scales="free") +
  guides(fill = guide_legend(override.aes = list(size=3))) +
  ylab("sampleID") +
  geom_xsidecol(aes(x = category, y=n, fill= category)) +
  geom_ysidecol(aes(y = sampleID, x = n ,fill = category))
```
when adding 
```
  scale_ysidex_continuous() +
  scale_xsidey_continuous()
```

I get: 
```
Error: Continuous value supplied to discrete scale
In addition: Warning messages:
1: In Ops.factor(x, range[1]) : ‘<’ not meaningful for factors
2: In Ops.factor(x, range[2]) : ‘>’ not meaningful for factors
3: In Ops.factor(x, range[1]) : ‘<’ not meaningful for factors
4: In Ops.factor(x, range[2]) : ‘>’ not meaningful for factors
5: In Ops.factor(x, range[1]) : ‘<’ not meaningful for factors
6: In Ops.factor(x, range[2]) : ‘>’ not meaningful for factors
```

**Comment by jtlandis** [comment]
Hello, I believe the Ops.factor warning is properly muffled in `ggside 0.2.1`. If you are not on that version, please reinstall from CRAN. 

I have confirmed that your code still does not add the side scales properly and it seems the issue is `facet_wrap(..., scales = "free")`. 

I'll investigate the issue. In the meantime, could you open a new issue with a minimal reprex that highlights when the side scales are not added?
