### ISSUE TITLE
How to put the position of side panel.

### ISSUE THREAD

**Issue by xiangpin** [jtlandis/ggside#37]
Thanks for the great package. The default of `ggside` seem to put the `xside` panel to top, and `yside` panel to the right of the main plot. whether can we also put `xside` panel to the bottom and `yside` panel to the left of the main plot?

![xx](https://user-images.githubusercontent.com/17870644/186822263-85c4d19a-1895-4e15-8be2-9fdc0510db86.PNG)

**Comment by jtlandis** [comment]
Hello, you can customize certain aspects of the side panels with the `ggside(...)` function. Please review the help documentation. Specifically you would want `ggside(x.pos = "bottom", y.pos = "left")`
