### ISSUE TITLE
Option to normalize density per groups

### ISSUE THREAD

**Issue by DominiqueMakowski** [jtlandis/ggside#38]
Hi! I'm making some side density plots grouped (by color and/or by facet), but sometimes due do the nature of density values there are huge differences of height between the groups, and it makes a not so nice plot. Would be cool to add the option to normalize the density per groups, so that all densities values (for each group) are in the same range? Something like the `normalize` argument in [ggdist](https://mjskay.github.io/ggdist/reference/stat_slab.html). thanks a lot!

**Comment by jtlandis** [comment]
Hello! Could you please provide an example of a plot with poor densities? you may be looking for `after_stat(scaled)` option. Let me know if the following reprex is what you mean.

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

set.seed(123)
df <- rbind(
  data.frame(g = "g1", x = rnorm(600, sd = 5), y = rnorm(600)),
  data.frame(g = "g2", x = rnorm(600, .7, 1.7), y = rnorm(600, .3, 8))
)

p <- ggplot(df, aes(x, y, color = g)) +
  geom_point() 

p 
```

![](https://i.imgur.com/dQGhLDf.png)

``` r

p + geom_xsidedensity() +
  geom_ysidedensity() +
  theme(ggside.panel.scale = .3)
```

![](https://i.imgur.com/y3Ey6gT.png)

``` r

p + geom_xsidedensity(aes(y = after_stat(scaled))) +
  geom_ysidedensity(aes(x = after_stat(scaled))) +
  theme(ggside.panel.scale = .3)
```

![](https://i.imgur.com/0IiNFhj.png)

<sup>Created on 2022-08-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DominiqueMakowski** [comment]
That did the trick! Thanks :)
