### ISSUE TITLE
Add Mean Comparison P-values to a ggplot

### ISSUE THREAD

**Issue by Luponsky** [jtlandis/ggside#42]
Hello,
Thanks to you for this fantastic package!
Could be possible to integrate the stat_compare_means of ggpubr to the side boxplot?
All the best,
L

**Comment by jtlandis** [comment]
I've been working pretty tirelessly on getting `ggside` to a place where it can function more seamlessly with `ggplot2`. I realize that there are other packages out there that would be interesting to apply to `ggside`, but I do not think this is and undertaking I want to do myself.

I have, however, put in some frameworks so people may extend `ggside` more easily. 

Currently, the `dev` branch of `ggside` can do what you are requesting. I am exporting a new function named `as_ggside_layer()` which will take a standard `LayerInstance` object and morph it into something that is compatible with `ggside` assuming that the correct `Geom(X|Y)side*` object may be found.

``` r
library(ggplot2)
library(ggside)
library(ggpubr)
ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "dose", palette = "npg")+
  stat_compare_means(method = "anova", label.y = 40)+ # Add global p-value
  as_ggside_layer(
    layer = stat_compare_means(aes(label = after_stat(p.signif)),
                       method = "t.test", ref.group = "0.5"),
    side = "x"
  ) +
  theme_ggside_void() +
  coord_cartesian(clip = "off")
```

![](https://i.imgur.com/kH2K7Qk.png)

<sup>Created on 2022-12-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This does not mean this will be sufficient with all cases. I was curious and messed around a bit, but not every package that extends `ggplot2` follows all of their conventions with their `ggproto` classes. Again, I think the current implementation on the `dev` branch is sufficient for now.

**Comment by IndrajeetPatil** [comment]
You might also want to have a look at [`{ggstatsplot}`](https://indrajeetpatil.github.io/ggstatsplot/), which creates ggplot objects with statistics.

E.g.

```r
set.seed(123)

ggbetweenstats(
  data  = iris,
  x     = Species,
  y     = Sepal.Length,
  title = "Distribution of sepal length across Iris species"
)
```

![image](https://user-images.githubusercontent.com/11330453/205319529-1c231e86-cabc-4b72-b819-d1b490a2f442.png)

**Comment by jtlandis** [comment]
`ggside` is moving forward with the release of `0.2.2` which will not include the features in development on the dev branch, namely making your own ggside layer on the fly. I will close this for now as you may have the option of using the dev branch of `ggside` or `ggstatplot` from @IndrajeetPatil for your needs.

Best
Justin

**Comment by Luponsky** [comment]
Thanks
