### ISSUE TITLE
Using expand argument with scale_ysidex_continuous

### ISSUE THREAD

**Issue by erbader** [jtlandis/ggside#44]
Hello!

Thanks for developing this nice package to make plotting easier :) I am trying to add some density plots to the y-axis side of my main plot and would like to remove the padding between the axes. I tried adding expand=c(0,0) to the scale_ysidex_continuous function, but it doesn't seem to remove the added space. I tested expand with ggplot geom_density and got it to work so I'm not sure if I've misunderstood some of the ggside documentation. Code and example of resulting plot below. 

ggplot(mtcars, aes(wt, mpg)) +
     geom_point() +
     geom_ysidedensity()  +
     scale_x_continuous(
         breaks = seq(1, 6, 1),
         #would otherwise remove the histogram
         #as they have a lower value of 0.
         limits = (c(1, 6))
     ) +
     scale_ysidex_continuous(expand = c(0,0))

![ggside_ysidex_continuous](https://user-images.githubusercontent.com/44820623/212786784-9b1c982f-c9f8-4685-8288-db3ce77a1173.png)

**Comment by jtlandis** [comment]
Hello, I'm glad you are finding `ggside` useful. I believe the feature you want is documented in ```?ggside::`ggside-theme` ```. Specifically, in this example, you should use `theme(ggside.panel.spacing.x = unit(0, "pt")` - this should remove all padding between the main panel and the yside panel.

``` r
library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  geom_ysidedensity() +
  theme(ggside.panel.spacing.x = unit(0, "pt"))
```

![](https://i.imgur.com/ABXz1TH.png)

<sup>Created on 2023-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by erbader** [comment]
Unfortunately, the suggested fix does not remove the padding on the x-axis of the side plot. What I'm trying to achieve is this:
`ggplot(mtcars, aes(x = wt)) + geom_density() + scale_x_continuous(expand = c(0,0))`
![scale_continuous_expand](https://user-images.githubusercontent.com/44820623/212887818-319ef8f6-3636-4fae-acfe-f25e0bf9b3cd.png)

The `expand` argument is available in `scale_ysidex_continuous`, but it doesn't seem to work as it does in ggplot.

**Comment by jtlandis** [comment]
@erbader Does this potentially address your issue?

**Comment by erbader** [comment]
Adding scale_y_continuous(expand = expansion()) to the main plot fixed the main issue. The proposed work-around to avoid points on the main plot falling on the axes is much appreciated. I haven't been able to implement the work-around solution, but will verify when/if I can!

**Comment by erbader** [comment]
Update: helper function works! 

In my actual data, I have a facet_wrap plot as the main plot I'm adding geom_ysidedensity to. As is, the helper function was adding an additional NA factor to the data, resulting in an empty facet for NA. Instead I used the helper function to define the y-axis limits and passed those to scale_y_continuous. Thank you for providing a solution so promptly!

**Comment by jtlandis** [comment]
I see, In the event you are using a facet_wrap in which each scale may change, you will need to modify the function such that it is done on each facet group. But I'm happy you have found your solution. Cheers!
