### ISSUE TITLE
allow collapsed sideplots with scales = "free"

### ISSUE THREAD

**Issue by Ihmor** [jtlandis/ggside#45]
Hey Justin! 

Thanks for the nice package! I've been enhancing my plots with it more and more, but ran into an issue with the changes in v0.2.2.
My usecase is to collpase a sideboxplot on the y-axis in a faceted plot. Here a reprex:

```
library(ggplot2)
library(ggside)

ggp <- ggplot(mtcars, aes(y = mpg, x = hp)) +
  geom_point() +
  ggtitle(label = paste("ggside", packageVersion("ggside"))) +
  facet_grid( vs ~ am, scales = "free")


# add y-collapsed sideboxplot
ggp + ggside::geom_ysideboxplot(aes(group = "all", x = "all"),
                                orientation = "x") +
  ggside::ggside(y.pos = "left", collapse = "y", scales = "fixed") +
  ggside::scale_ysidex_discrete()

```
With 0.2.1, this creates the expected plot:
![image](https://user-images.githubusercontent.com/12380861/232007818-e4285ba2-1491-43de-bedb-a695292e3c26.png)

With 0.2.2, `collapse = "y"` is not allowed with `scales = "free"` or `"free_y"`, overwriting it to `collapse = NULL`. 
![image](https://user-images.githubusercontent.com/12380861/232009301-60975172-1607-4222-8af3-e8eb14536d4f.png)

For me, the v0.2.1 plot is a reasonable usage of a sideboxplot and `collapse = NULL` does not have to be enforced. Though I don't have a full understanding of all use cases of ggside.  Maybe I am misuing ggside with `group = "all"`.

The enforcement was added due to [issue 35](https://github.com/jtlandis/ggside/issues/35). 

What do you think? Is there a way to allow for both use cases?

Kind regards, 
Phillip

**Comment by jtlandis** [comment]
Hello Phillip,

This warning is triggered when `ggside(..., collapse = c("y", "x", "all"))` is provided AND the facet layer's associated `scales` parameter is set to some "free" variant.

The main reason this was excluded was to inform the user that "free" scales are not always compatible with facets, especially if multiple panels share the same axis.

Unfortunately, when I was adding this feature, I mostly only had in mind the case with `facet_wrap()` and failed to consider how differently `facet_grid()` works

I believe you are correct that it does not need to be enforced. `facet_grid(..., scales = "free")` forces all panels in a row to have the same y-axis scale and all the panels in a column to share the same x-axis scale, which would work nicely with the `collapse` argument of `ggside()`.

I think this should be an easy fix to implement - We would only throw this warning if the facet layer inherits from "FacetWrap".

I do not know when I will get to making a new release as life is getting a bit busy. 

Thank you for bringing this to my attention!

**Comment by jtlandis** [comment]
I've pushed a small edit to the source code and you should be able to install this version of ggside with `remotes::install_github("jtlandis/ggside")`

Now the warning will only present when the facet inherits from `FacetWrap`. I will close this issue for now.

**Comment by Ihmor** [comment]
Hi Justin, 

The fix works well for my use case. Thanks for the considerations and work! 

Kind regards, 
Phillip
