### ISSUE TITLE
ggside doesn't work with coord_cartesian

### ISSUE THREAD

**Issue by The-Dub** [jtlandis/ggside#55]
Hello,

First of all thank you for this wonderful package, that makes it very easy to add marginal distribution.

I have encountered an issue that is easily reproducible : when using `ggplot::coord_cartesian`, it changes the x and y lim of the main plot, but also the limits of the xside and yside, that is not a wanted behavior, from what I understand. 
```{r}
library(tidyverse)
library(ggside)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point(size = 2) +
  geom_xsidedensity(aes(y = after_stat(density)), position = "stack") +
  geom_ysidedensity(aes(x = after_stat(density)), position = "stack") +
  theme(axis.text.x = element_text(angle = 90, vjust = .5)) + 
  coord_cartesian(xlim = c(3, 6), ylim = c(20, 30))
```

I have tried to overwrite this behavior with  `scale_xsidey_continuous ` and `scale_ysidex_continuous ` without any success. I have found the function `as_ggsideCoord` but I'm unsure how this function works. The `ggside` documentation  for the `scale*_side_function` states that one should use coord_cartesiant ("If the purpose is to zoom, use the limit argument in the coordinate system (see coord_cartesian()).")

Thank you for the help

**Comment by jtlandis** [comment]
Thankfully, this should was a relatively easy hotfix in c6c108220452c519b64f8e1afcedf792311572b7 that I could complete this in a day. If you find any more errors or unexpected behaviors, please do not hesitate to drop another issue.
