### ISSUE TITLE
Strange variable handling inside functions

### ISSUE THREAD

**Issue by smped** [jtlandis/ggside#58]
Hi @jtlandis ,

Great work getting `ggside` ready for the breaking `ggplot2` changes! That was such brilliant fast work. 

Unfortunately, I've found a weird quirk in the new version & I don't know if it's connected to their new updates. In short, passing values to `ggside` geoms inside a function has gone a bit strange.

``` r
p <- mtcars |>
    dplyr::mutate(cyl = as.factor(cyl)) |>
    ggplot(aes(mpg, hp)) +
    geom_point() 
## Looks about right
p

.addSide <- function(p, my_alpha) {
    message("my_alpha is: ", my_alpha)
    p + geom_ysideboxplot(
        aes(x = cyl, y = hp, fill = cyl), orientation = "x",
        alpha = my_alpha
    )
}
.addSide(p, 0.5)
```

To which I get `Error in eval(call, envir = env) : object 'my_alpha' not found`, which is clearly a bit of a glitch because it's there in the message line. For context, the function I've just disabled this behaviour in is at https://github.com/smped/extraChIPs/blob/devel/R/plotPairwise.R. It did used to work rather nicely until this update.

I'm sure you've spotted it too but, on Ubuntu 20.04 at least, the old warnings have made a comeback. Really just a niggle as it's not causing my tests or checks to fail

```
Warning messages:
1: In Ops.factor(x, range[1]) : '<' not meaningful for factors
2: In Ops.factor(x, range[2]) : '>' not meaningful for factors
```

**Comment by jtlandis** [comment]
Thank you for reporting!
I'm surprised that there are issues with `extraChIPs` considering nothing came up in revdep checks. I'll have to investigate the logs further.

I'll see if I can get a hot fix and a new unit test up

**Comment by jtlandis** [comment]
hello @smped, please see if the latests commits (f04fee5) main branch builds and passes tests with `extraChIPs` package.

**Comment by jtlandis** [comment]
It seems that `revdepcheck` tends to timeout, (no matter how much time I give to `timeout =`). I was able to complete a `R CMD check` on the `.tar.gz` for `extraChIPs` but I would still appreciate a double check @smped before I push this hotfix to CRAN

**Comment by smped** [comment]
Hi @jtlandis ,

Amazing work again! Thanks for keeping on top of things like you have. My local tests are now passing, which is great news.

All the best

**Comment by jtlandis** [comment]
Alright, I'll try and resubmit this afternoon.

**Comment by jtlandis** [comment]
@smped CRAN was fairly kind and uploaded the hotfix
