### ISSUE TITLE
Remove numbers and ticks from sides' axes only

### ISSUE THREAD

**Issue by DominiqueMakowski** [jtlandis/ggside#7]
Hi and thanks for your package, I've been looking for something like that for some time.

I have a question, is it possible to remove the axes numbers and ticks of the sides only?

Thank you!

``` r
library(ggplot2)
library(ggside)

ggplot(mtcars, aes(mpg, wt)) + 
  geom_point(size = 2) +
  geom_xsidedensity(aes(y = stat(density))) +
  geom_ysidedensity(aes(x = stat(density))) 
```

![](https://i.imgur.com/kFaUMjO.png)

<sup>Created on 2021-05-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
Also, as a somewhat related follow-up question, to make the y-axis of the sides to have a [zero-origin](https://stackoverflow.com/questions/13701347/force-the-origin-to-start-at-0)? So that the density lines appear as closer to the main plot? Thanks again ☺️

**Comment by jtlandis** [comment]
Hello! I'm glad this package has been impactful!

This has been something I wanted to address but will definitely need some time to flesh out an API that makes sense. 

Right now, I don't see any issue with adding theme elements that control how the axis texts are rendered, but I wont know until I try.

When it comes to a `zero-origin` this will require more thought. To achieve this we would either need to leverage the `expand` logic that exists in the `scale_*_continuous()`/`scale_*_discrete()`, or side step it completely and figure out how to set coordinate limits per panel.

I'll post again when I've made any developments towards this.

Thanks again!

**Comment by jtlandis** [comment]
I put in a bit of work and thought of a way to handle making a custom axis for the side panels by taking inspiration from [@paleolimbot 's blog post](https://fishandwhistle.net/post/2018/modifying-facet-scales-in-ggplot2/)

With the `scale_xsidey_continuous` and `scale_ysidex_continuous` functions, you will be able to specify virtually everything about the side panel axises. See the examples below:

``` r
library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

ggplot(mtcars, aes(mpg, wt)) + 
  geom_point(size = 2) +
  geom_xsidedensity(aes(y = stat(density)),) +
  geom_ysidedensity(aes(x = stat(density)),) +
  scale_xsidey_continuous(breaks = NULL, labels = "", expand = expansion(c(0,.1))) +
  scale_ysidex_continuous(breaks = NULL, labels = "", expand = expansion(c(0,.1))) 
```

![](https://i.imgur.com/hx1w3JR.png)

`xsidey` indicates the y axis on the xside panel, and `ysidex` indicates the x axis on the yside panel.

This also helps solve the issue I was facing with #6 where I want to be able to allow mixing of continuous and discrete axes. I haven't had a chance yet to test all possible cases of this mixing - i.e. with different Facet variants, so it may be buggy.

``` r

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(size = 2) +
  geom_xsideboxplot(aes(y = class), orientation = "y") +
  geom_ysidedensity(aes(x = stat(density)),) +
  scale_xsidey_discrete() +
  scale_ysidex_continuous(breaks = NULL, labels = "", expand = expansion(c(0,.1))) +
  theme(
    ggside.panel.scale.x = .3
  )
```

![](https://i.imgur.com/UQNvwJ7.png)

Eventually I would like to add more theme elements for the side panels, but I think this is sufficient for now.

Right now, this should be available on the dev branch of this repository. Please have a go at it and let me know if you find any bugs.



<sup>Created on 2021-05-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
Awesome, thanks a lot!! I'll give it a try asap :)

**Comment by DominiqueMakowski** [comment]
(hey, sorry for the delay, but just wanted to say that it works like a charm! thanks again for that very useful package :)
